version: '3.9'

services:
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - "80:8080"

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: human_friends
    ports:
      - "3806:3306"
    volumes:
      - ./docker_db:/var/lib/mysql

