version: '3.9'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: human_friends
    ports:
      - "3806:3306"
    volumes:
      - ./docker_db:/var/lib/mysql

